### ISSUE TITLE
see you some upgrade to JupyterLab 3.1.0 in your roadmap?

### ISSUE THREAD

**Issue by pflegende** [ReviewNB/jupyterlab-gitplus#12]
Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.4 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application

**Comment by amit1rrr** [comment]
Upgraded to be compatible with JupyterLab 3.x

Please use the latest version - https://pypi.org/project/jupyterlab-gitplus/0.1.8/#history
