### ISSUE TITLE
[ValueError] The extension "@reviewnb/jupyterlab_gitplus" does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by euisuk-chung** [ReviewNB/jupyterlab-gitplus#27]
Hello I am using JupyterLab 3.5.1, and I've ran into this problem of "conflicting dependencies" between "@lumino/application" and my current JupyterLab version.

---
Conflicting Dependencies:
JupyterLab          Extension       Package
>=1.31.3 <2.0.0     1.13.1          @lumino/application
---

![image](https://user-images.githubusercontent.com/44948482/217730762-0660e9ee-39c6-4682-9937-44006116d66b.png)

According to the readme, it is suppose to work out with JupyterLab 3.5(3.X).

**Comment by amit1rrr** [comment]
@euisuk-chung We've released a new version of the extension that is supposed to be compatible with 3.5.x - https://www.npmjs.com/package/@reviewnb/jupyterlab_gitplus/v/0.1.6

Can you try installing the extension again please?

**Comment by euisuk-chung** [comment]
It works fine now :) THX you
