### ISSUE TITLE
"Error loading server extension jupyterlab_gitplus.extension"

### ISSUE THREAD

**Issue by hellojinwoo** [ReviewNB/jupyterlab-gitplus#8]
First of all, thank you for making such a wonderful jupyterlab extension. But I have a problem, which I would appreciate if you can help me to solve.

## Problem
 - I cannot finish installing the jupyterlab_gitplus.
 - The line of code that gives me a problem is __`jupyter serverextension enable --py jupyterlab_gitplus`__

## Detail of the problem
 - I am using Windows 10, so I opened cmd.exe to install jupyterlab-gitplus, as shown in the instruction. 
 ```
pip install --upgrade jupyterlab_gitplus
jupyter labextension install @reviewnb/jupyterlab_gitplus
jupyter serverextension enable --py jupyterlab_gitplus
```
First two lines of codes worked fine, but the last code, `jupyter serverextension enable --py jupyterlab_gitplus` gave me the error line as shown below.

- __Error Message__
```
C:\Users\Jinwoo_PARK_NANTIER>jupyter serverextension enable --py jupyterlab_gitplus
Enabling: jupyterlab_gitplus.extension
- Writing config: C:\Users\Jinwoo_PARK_NANTIER\.jupyter
    - Validating...
Error loading server extension jupyterlab_gitplus.extension
      X is jupyterlab_gitplus.extension importable?
```
- What can I do to solve this problem?

## Environment
- OS : Windows 10
- Jupyterlab : Version 2.1.5
- Python : Version 3.8.3

**Comment by amit1rrr** [comment]
Your problem might be that `pip` uses a different python installation than what your `jupyter` uses. Here's how you can confirm this -

1. Run following in jupyter notebook and see output:
```
import sys
sys.executable
```

2. Then run `which python` (or whatever is the windows equivalent of this) on command prompt and see the python path. This path should be the same as the path you get in jupyter. If they are different, that is the issue.

If above is your issue then simply install  `jupyterlab_gitplus` python package under your jupyter's python installation as shown below:

```
<python-path-from-step1-output-abve> -m pip install jupyterlab_gitplus
```

**Comment by hellojinwoo** [comment]
I could not find the equivalent thing of `which python` on windows, so uninstalled and installed anaconda again. and it solved the problem.
