### ISSUE TITLE
"Failed to fetch list of repositories. Have you installed & enabled server side of the extension?" 

### ISSUE THREAD

**Issue by hellojinwoo** [ReviewNB/jupyterlab-gitplus#9]
I appreciate your wonderful jupyterlab extension __`jupyterlab-gitplus`__. But can you help me deal with another issue, please?

# Issue
- I also encounter error message saying 'Failed to fetch list of repositories. Have you installed & enabled server side of the extension?', which is mentioned in the thread  #5 
![image](https://user-images.githubusercontent.com/34431729/97454568-33ed0880-1937-11eb-9d3c-1f7a6f7dc3bf.png)

### 1. jupyter serverextension list
- I ran the code __`jupyter serverextension list`__ to check if the extension is enabled for your Jupyter installation. As it is shown in the screenshot below, __`jupyterlab_gitplus.extension`__ is enabled

![image](https://user-images.githubusercontent.com/34431729/97455078-bbd31280-1937-11eb-91ab-804c2ef320ec.png)

### 2. Error logs
- The screenshot below is an error log when I clicked __`create pull request`__ in the gitplus tab. 
(The error logs start right after the red underline)

![image](https://user-images.githubusercontent.com/34431729/97454255-d6f15280-1936-11eb-8e9b-3bfaf29d9dd3.png)

Just in case you cannot see the screenshot clearly, I also copy&pasted the error codes for you. 

```
gitplus/modified_repo request payload: [{'path': 'C:\\Users\\Jinwoo_PARK_NANTIER\\Desktop\\Codes/Creating RL environment/sentex/.ipynb_checkpoints/4. our own environment-checkpoint.ipynb'}, {'path': 'C:\\Users\\Jinwoo_PARK_NANTIER\\Desktop\\Codes/Creating RL environment/sentex/4. our own environment.ipynb'}]
Traceback (most recent call last):
  File "C:\Users\Jinwoo_PARK_NANTIER\anaconda3\lib\site-packages\jupyterlab_gitplus\handlers.py", line 40, in post
    if GITHUB_REMOTE_DOMAIN not in repo.remotes.origin.url:
  File "C:\Users\Jinwoo_PARK_NANTIER\anaconda3\lib\site-packages\git\util.py", line 882, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'

[E 16:12:28.950 LabApp] Uncaught exception POST /gitplus/modified_repo (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/gitplus/modified_repo', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\Jinwoo_PARK_NANTIER\anaconda3\lib\site-packages\tornado\web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jinwoo_PARK_NANTIER\anaconda3\lib\site-packages\jupyterlab_gitplus\handlers.py", line 62, in post
        raise(ex)
      File "C:\Users\Jinwoo_PARK_NANTIER\anaconda3\lib\site-packages\jupyterlab_gitplus\handlers.py", line 40, in post
        if GITHUB_REMOTE_DOMAIN not in repo.remotes.origin.url:
      File "C:\Users\Jinwoo_PARK_NANTIER\anaconda3\lib\site-packages\git\util.py", line 882, in __getattr__
        return list.__getattribute__(self, attr)
    AttributeError: 'IterableList' object has no attribute 'origin'
[E 16:12:28.953 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "277",
      "Accept": "application/json, text/plain, */*",
      "X-Csrftoken": "2|367d94c6|72f9eff6e34831a0cf6690ebacb4f0c2|1602060128",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Whale/2.8.107.16 Safari/537.36",
      "Content-Type": "application/json;charset=UTF-8",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,ko;q=0.8,ko-KR;q=0.7",
      "Cookie": "_xsrf=2|367d94c6|72f9eff6e34831a0cf6690ebacb4f0c2|1602060128; username-localhost-8889=\"2|1:0|10:1603891078|23:username-localhost-8889|44:YzhhZTU4NDZiNmQ5NDMzN2FiYjExYjcyZjhjNDRmOGY=|cce550b48f85440e8c1d997ec02f87e168f4672208cb17027a800cb720d778f1\"; username-localhost-8888=\"2|1:0|10:1603897943|23:username-localhost-8888|44:ZGJmYzJmYjc4MTA5NDBmN2E3Y2Q5YzJkYzcwOWU3ZGY=|392bd7f760ca8a877464907dbd1d570626604bc535d995c611251992e1d56292\""
    }
[E 16:12:28.953 LabApp] 500 POST /gitplus/modified_repo (::1) 8.00ms referer=http://localhost:8888/lab
```

### 3. Setting up github tokens
- I also have set up github tokens. In the folder __`C:/Users/[user_name]/.jupyter`__, I have two files, __`jupyter_notebook_config.py`__ and __`jupyter_notebook_config.json`__. besides a folder called __`lab`__.

- In the __`jupyter_notebook_config.py`__ file, I added my github token as shown below. (While all other codes are commented, the line that I added __`c.GitHubConfig.access_token = 'f85c....`__ is not commented. Is it okay to do so?)

![image](https://user-images.githubusercontent.com/34431729/97457374-fb026300-1939-11eb-8ff4-7b1802d9989f.png)

- In the __`jupyter_notebook_config.json`__, it is written as belows.
```
{
  "NotebookApp": {
    "nbserver_extensions": {
      "jupyterlab_gitplus.extension": true
    }
  }
}
```

**Comment by amit1rrr** [comment]
Thanks for the detailed information. The error seems to be coming from GitPython. Specifically it is unable to detect remote origin. I'd advise trying two things -

- Can you run `git remote -v` on cmdline under the repository (`cd` into it) on which you are seeing this error. Please share the output.

- Can you make fresh clone of this repository and try our extension on it?

**Comment by hellojinwoo** [comment]
- First of all, please bear with me, because I am a newbie to the programming language __`git`__
## 1st thing
- I have executed __`create pull request`__ of the git-plus tab in the folder __`C:\Users\Jinwoo_PARK_NANTIER\Desktop\Codes\Creating RL environment\sentex`__ 
- On the cmd, I entered this folder using __`cd`__ and did __`git remote -v`__ but nothing happens, as shown below. ( Did I do this right?)
![image](https://user-images.githubusercontent.com/34431729/97462493-1328b100-193f-11eb-9970-bf63440d5bc3.png)

## 2nd thing
- Are you saying that you want me to copy my folder __`sentex`__ somewhere else like __`download`__ folder and execute the __`Create Pull Request`__?

**Comment by amit1rrr** [comment]
> On the cmd, I entered this folder using cd and did git remote -v but nothing happens, as shown below. ( Did I do this right?)

Yes, you did it correctly. Is this `sentex` folder a git repository? Did you just create this repository locally or did you download/clone it from GitHub? 


>Are you saying that you want me to copy my folder sentex somewhere else like download folder and execute the Create Pull Request?

No, this repository must be available somewhere on GitHub right? E.g. [this one](https://github.com/hellojinwoo/CA_GMVP) so  you need to lookup your repository on GitHub and then run `git clone <repository-url>`, this will basically pull in a fresh copy of this repository from GitHub. (think of repository as folder on GitHub)

**Comment by amit1rrr** [comment]
By the way, if you're just starting out with Git you will find this tutorial blogpost very useful: https://blog.reviewnb.com/github-jupyter-notebook/

**Comment by hellojinwoo** [comment]
Thank you for sharing the nice blog post about how to use jupyter notebook/ jupyter lab with github. My primary IDE is jupyter lab so it is really a nice resource to me. Let me answer your questions with bullet points.

- __The source of the folder `sentex`__ : The folder __`sentex`__ is the local folder that I made. I did not clone/download this folder from github, because the ipynb file inside this folder is based on a blog post ['Q-Learning In Our Own Custom Environment....'](https://pythonprogramming.net/own-environment-q-learning-reinforcement-learning-python-tutorial/). Since the author of this blog post uploaded the code on the blogs, I created the folder sentex (the name of the youtuber/blog owner) and then copied the codes and put it on my __`ipynb`__ file.

- __What I am trying to do__ : I intend to upload my ipynb files in my local environment to private github repositories, so that I can access them regardless of devices that I use. --> You thought that I cloned the __`sentex`__ folder from somewhere in the github from a user, but I created the folder locally. Would it be a problem to solve my issue? 

-  __Question__ : Does __`jupyterlab-gitplus`__ support private repositories in github as well?

**Comment by amit1rrr** [comment]
> I intend to upload my ipynb files, which are located in my local environment, to the private github repositories, so that I can access them regardless of devices that I use.

Got it. For this you need to create a repository on GitHub & then push your files to it. Just follow the steps in this [blog](https://blog.reviewnb.com/github-jupyter-notebook/).

> Does jupyterlab-gitplus let me push my ipynb or python files to private repositories on github as well?

Yes, it works with private repositories as well. Extension can push files to an existing repository but the extension can't create a new GitHub repository for you (it doesn't have that functionality yet). So you need to follow the steps in the blogpost & create a new repository yourself. Then you will be able to use `jupyterlab-gitplus` extension to push new files & modifications to the repository.

**Comment by hellojinwoo** [comment]
- Just for your information, I use the library [__`jupyterlab-github`__](https://github.com/jupyterlab/jupyterlab-github) as well, and users need to install serverextensions ([reference](https://github.com/jupyterlab/jupyterlab-github),  in the exactly same way as we need to install serverextensions in __`jupyterlab-gitplus`__. 

- I can use the __`jupyterlab-github`__ without any problem.

**Comment by amit1rrr** [comment]
> Now the only problem seems to be that I cannot use the library jupyterlab-gitplus on my jupyter lab...

As I mentioned, `jupyterlab-gitplus` works only **after** Git repository is setup. Creating new repository etc. is not yet supported in `jupyterlab-gitplus`
